version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    day: friday
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: "json-server"
  - dependency-name: eslint


updates:
- package-ecosystem: nuget
  directory: "/server/"
  schedule:
    interval: weekly
    day: friday
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 1

updates:
- package-ecosystem: "devcontainers"
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 1

updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 1
