name: Client Build

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/client.yml"
      - "client/**"
    branches: 
    - main
  
  pull_request:
    paths:
      - ".github/workflows/client.yml"
      - "client/**"
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      DOCKER_BUILDKIT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build
      run: docker build -f ./client/Dockerfile -o ./artifacts/test-results --target test-result ./client

    - name: Publish Test Results
      uses: actions/upload-artifact@v3.1.1
      with:
        name: TestReport
        path: ./artifacts/test-results/

    # - name: Build
    #   if: github.ref == 'refs/heads/main'
    #   run: docker build -t image . && docker save image -o artifacts\image.tar
